version: '3'
services:
  arcide:
    image: triplai/arc-jupyter:arc-jupyter_1.9.3_scala_2.12_hadoop_2.9.2_1.0.0
    command:
      - start-notebook.sh
      - --NotebookApp.password=''
      - --NotebookApp.token=''
    ports:
      - "8888:8888"
      - "4040:4040"
    volumes:
      - "./data:/data"
      - "./src:/home/jovyan/src"
      - "./model:/model"
